{
 "title": "Покемоны",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "Общая статистика боев:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), AVG(rounds_count) FROM \"Core_fightresult\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество боев за последние 2 недели",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), battle_date::DATE\r\nFROM \"Core_fightresult\"\r\nGROUP BY battle_date::DATE\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Топ-5 покемонов",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as wins, player_pokemon\r\nFROM \"Core_fightresult\"\r\nwhere result = True\r\ngroup by player_pokemon\r\nUNION ALL\r\nSELECT COUNT(*) as wins, opponent_pokemon\r\nFROM \"Core_fightresult\"\r\nwhere result = False\r\ngroup by opponent_pokemon\r\norder by wins desc\r\nlimit 5"
    }
   ]
  },
  {
   "title": "количество раундов за последние 2 недели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT Sum(rounds_count), battle_date::DATE\r\nFROM \"Core_fightresult\"\r\nGROUP BY battle_date::DATE"
    }
   ]
  }
 ]
}